name: tests
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo build --verbose
      - run: cargo test --all-features
      - run: cargo clippy --verbose -- -D warnings
